AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  followercount

  SAM Template that counts followers over time

Parameters:
  twooters:
    Type: String
    Default: Quinnypig

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tags:
      project: followercount
    Environment:
      Variables:
        TWITTER_ACCOUNTS: !Ref twooters
        TABLE_NAME: !Ref FollowerCount

Resources:
  PopularFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mr_popular/
      Handler: mrpopular.handler
      Runtime: python3.8
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: TWITTER_BEARER_TOKEN
        - DynamoDBWritePolicy:
            TableName: !Ref FollowerCount
      Tags:
        project: followercount
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Description: Once an hour
            Enabled: True

  FollowerCount:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: twitter_handle
          AttributeType: "S"
        - AttributeName: EpochTime
          AttributeType: "N"
      KeySchema:
        - AttributeName: "twitter_handle"
          KeyType: "HASH"
        - AttributeName: "EpochTime"
          KeyType: "RANGE"
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PopularFunction:
    Description: "Popular Lambda Function ARN"
    Value: !GetAtt PopularFunction.Arn
  PopularFunctionIamRole:
    Description: "Implicit IAM Role created for Popular function"
    Value: !GetAtt PopularFunctionRole.Arn
